# Default initial positions for arm_dualarm's ros2_control fake system

initial_positions:
  j1_Joint_L: 0
  j1_Joint_R: 0
  j2_Joint_L: 0
  j2_Joint_R: 0
  j3_Joint_L: 0
  j3_Joint_R: 0
  j4_Joint_L: 0
  j4_Joint_R: 0
  j5_Joint_L: 0
  j5_Joint_R: 0
  j6_Joint_L: 0
  j6_Joint_R: 0