# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - j1_Joint_L
      - j2_Joint_L
      - j3_Joint_L
      - j4_Joint_L
      - j5_Joint_L
      - j6_Joint_L
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - j1_Joint_R
      - j2_Joint_R
      - j3_Joint_R
      - j4_Joint_R
      - j5_Joint_R
      - j6_Joint_R
    action_ns: follow_joint_trajectory
    default: true