# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - j1_Joint_L
      - j2_Joint_L
      - j3_Joint_L
      - j4_Joint_L
      - j5_Joint_L
      - j6_Joint_L
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_arm_controller:
  ros__parameters:
    joints:
      - j1_Joint_R
      - j2_Joint_R
      - j3_Joint_R
      - j4_Joint_R
      - j5_Joint_R
      - j6_Joint_R
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity